### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function __construct()

### ISSUE THREAD

**Issue by magicsunday** [TYPO3/Fluid.SchemaGenerator#12]
The command fails if a view helper contains a constructor with arguments (loaded with dependency injection).

Fatal error: Uncaught ArgumentCountError: Too few arguments to function MyViewHelper::__construct(), 0 passed in /var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php on line 46 and exactly 1 expected in /var/typo3-10/app/public/typo3conf/ext/my-extension/Classes/ViewHelpers/MyViewHelper.php on line 37

Call Stack:
    0.0002     415200   1. {main}() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/bin/generateschema:0
    0.0091    1470840   2. TYPO3\FluidSchemaGenerator\SchemaGenerator->generateXsd() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/bin/generateschema:47
    0.0124    1605096   3. TYPO3\FluidSchemaGenerator\SchemaGenerator->generateXmlForClassName() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php:72
    0.0125    1605960   4. TYPO3\FluidSchemaGenerator\SchemaGenerator->addAttributes() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php:142
    0.0125    1605960   5. TYPO3\FluidSchemaGenerator\ViewHelperDocumentation->getArgumentDefinitions() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php:156
    0.0125    1605960   6. TYPO3\FluidSchemaGenerator\SchemaGenerator->TYPO3\FluidSchemaGenerator\{closure:/var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php:45-47}() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/ViewHelperDocumentation.php:69
    0.0125    1606184   7. Netresearch\NrcStockList\ViewHelpers\Uri\IndexViewHelper->__construct() /var/typo3-10/app/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php:46

**Comment by NamelessCoder** [comment]
You should be able to work around this by:

* Copying `bin/generateschema` to another location+name
* Adjusting the call to `$generator->generateXsd($namespaceClassPathMap);` to add a second argument, which must be a closure that accepts a single string argument and which uses whichever method to instance the classes that your use case requires.

In general I would recommend not relying on constructor injections for two reasons:

* It makes the ViewHelper class unable to function outside of a specific framework context
* It does not inject the dependency from within compiled Fluid templates if you implement `renderStatic` (which is the best performing method for Fluid 2.x)
