### ISSUE TITLE
[BUG] PHP Fatal error:  Uncaught Error: Call to a member function getMethodParameters()

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [TYPO3/Fluid.SchemaGenerator#5]
Running `./vendor/bin/generateschema TYPO3\\CMS\\Fluid` on version 8 LTS (composer ^8.7) and Fluid.SchemaGenerator (composer dev-master) I get following error:

```bash
PHP Fatal error:  Uncaught Error: Call to a member function getMethodParameters() on null in /var/www/vendor/typo3/cms/typo3/sysext/fluid/Classes/Core/ViewHelper/AbstractViewHelper.php:119
Stack trace:
#0 /var/www/vendor/typo3/cms/typo3/sysext/fluid/Classes/Core/ViewHelper/AbstractViewHelper.php(163): TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper->registerRenderMethodArguments()
#1 /var/www/vendor/typo3/fluid-schema-generator/src/ViewHelperDocumentation.php(69): TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper->prepareArguments()
#2 /var/www/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php(144): TYPO3\FluidSchemaGenerator\ViewHelperDocumentation->getArgumentDefinitions()
#3 /var/www/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php(130): TYPO3\FluidSchemaGenerator\SchemaGenerator->addAttributes(Object(TYPO3\FluidSchemaGenerator\ViewHelperDocumentation), Object(SimpleXMLElement))
#4 /var/www/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php(62): TYPO3\FluidSchemaGenerator\SchemaGenerator->g in /var/www/vendor/typo3/cms/typo3/sysext/fluid/Classes/Core/ViewHelper/AbstractViewHelper.php on line 119
```
I ended up using your https://fluidtypo3.org/schemas/fluid-master.xsd :)

**Comment by NamelessCoder** [comment]
Phew, okay, so this one has quite a lot of things to explain - I'll try to make this quick:

* The main issue is that the `new` keyword is used to make class instances which doesn't then perform the injection that is required for the `reflectionService` attribute to be filled on CMS ViewHelpers - which is required for render method argument support to function.
* I made a quick test locally if it is enough to specify a different RenderingContext class (it is for the prewarming tool I made) - however, that's not enough for generating ViewHelper docs. Among other problems, there are errors about undefined caches (`extbase_object` which is essential to object instanciation and injection). I've prepared https://review.typo3.org/#/c/52415/ which solves part of this, https://review.typo3.org/#/c/52416/ which solves yet another part and have a final plan to deprecated the `LF` constant in favor of `PHP_EOL` which does not have to be declared by runtime like `LF` does. With those three changes plus a feature for this package to allow setting a custom `RenderingContext` class name actually allows XSD generation on 8.7 without a wrapper script.
* But for the time being it looks like this would *have* to be wrapped in a TYPO3 environment for it to work, which would imply adding this package as dependency and using a custom `ViewHelperDocumentation` class which uses `ObjectManager` to load VH instances.
* There is also a schema generating sub-command in `typo3_console` and I've suggested to @helhum that maybe we can use this package as dependency and provide the schema generating command (with input arguments pre-tailored for CMS, e.g. no arguments means generate `f:` namespace). The long-term perspective for that would be that XSD generation becomes a built-in feature of TYPO3 (both on CLI and using PHP API) when `typo3_console` becomes a core dependency.
* Long (**long**) term goal is to deprecate render method argument support in TYPO3 CMS and later remove the overridden abstract classes and with them, the need for `ReflectionService`. When that happens, this package will be able to generate schemas without anything except the target package containing the ViewHelpers to generate XSD for (e.g. it would work in CI and local dev if you `require --dev` this package).

Hopefully that explains the entire situation and which steps to take next!

**Comment by NamelessCoder** [comment]
Best I can do for now: https://github.com/FluidTYPO3/fluidtypo3-development has been updated to add a CLI command that allows generating ViewHelper schemas while faking a lot of the otherwise necessary TYPO3 context. It's enough to generate ViewHelpers for the TYPO3 core and Flux and VHS but I haven't tested it on other candidates.

A better solution for this problem has to be achieved via for example typo3_console, see https://github.com/TYPO3-Console/typo3_console/pull/413

**Comment by simonschaufi** [comment]
I found a similar extension which actually works for TYPO3 8 
https://github.com/FluidTYPO3/schemaker/

The problem described here works there as they use:

```php
$viewHelper = $this->objectManager->get($className);
```
to get the Viewhelper which also injects the reflectionService. See: https://github.com/FluidTYPO3/schemaker/blob/development/Classes/Service/SchemaService.php#L244-L246

**Comment by NamelessCoder** [comment]
Work is in progress trying to convince TYPO3 CMS to drop those ViewHelper base class overrides that impose the requirement for ObjectManager loading on *every* ViewHelper class.

* https://review.typo3.org/52796 and subsequent removal of the business logic is key
* https://github.com/TYPO3/Fluid/pull/271 in upstream used by TYPO3 CMS will replace the custom error handling TYPO3 CMS uses
* A future patch to deprecate/remove a few properties on TYPO3 CMS abstract ViewHelper classes is the final piece to the puzzle.

Once those are all gone, schemas can be generated completely without any TYPO3 context.

**Comment by simonschaufi** [comment]
The question is: do you want to make this extension compatible with v8 or do you want to wait until all the stuff is merged and a new TYPO3 release comes out?

**Comment by NamelessCoder** [comment]
> do you want to make this extension compatible with v8 or do you want to wait until all the stuff is merged and a new TYPO3 release comes out?

If I understand that correctly and by "this extension" you mean `typo3/fluid-schema-generator` then no, I don't expect that will become directly compatible with TYPO3v8. Instead I expect to use `typo3/fluid-schema-generator` in EXT:schemaker and raise the minimum requirement to TYPO3 8.7. This is possible because the schema generator can be used with TYPO3v8, it just can't be used without the existing bootstrapping or a custom bootstrapping and my attempts to add various native TYPO3 features that would allow that, have all been rejected.

That being said, `typo3/fluid-schema-generator` will work directly with TYPO3v9, if you just stay away from using the deprecated render method arguments. Once https://review.typo3.org/#/c/53199/ is merged that compatibility is achieved, but you have to avoid use of render method arguments because any such use will trigger multiple TYPO3 framework features that require caches and so on.

**Comment by simonschaufi** [comment]
it's merged!

**Comment by NamelessCoder** [comment]
Required patch is now merged - if you're interested, you should now be able to generate schemas for your ViewHelpers if you use TYPO3 master branch and avoid render method arguments.
